### ISSUE TITLE
failed to recognize the AppID of a collection

### ISSUE THREAD

**Issue by Noellelivinggayness** [alpergur13/SteamModDownloader#5]
"Could not determine AppID for this collection"

you could add an option to manually set the AppID separately from the collection ID for these cases

**Comment by Noellelivinggayness** [comment]
also another possible issue some NSFW mods will fail without an account so you should also add an optional option for signing in

**Comment by alpergur13** [comment]
We didn't think about NSFW ones, maybe in a future update, just maybe though.
We will look into the other issue, but if you can share the whole package that would be good to try and fix.

**Comment by Noellelivinggayness** [comment]
actually it's not related to whether or not it's NSFW I think it might be controlled by the devs or maybe it's just random also I tried a lot and couldn't get the tool to work this did work on another tool so sorry I won't try to bug test this anymore the collection I tried downloading is [this one](https://steamcommunity.com/workshop/filedetails/?id=3153577232) warning highly NSFW in fucked up ways importing the collection failed so I tried to create a file myself with this script:
```
#!/usr/bin/env bash

set -e

# cock and balls torture CBT is a sexual activity incolving the infliction of pain or contriction of the males genitals
DEPENDENCIES=("python3" "curl" "grep")

missing_deps=()

echo "Checking dependencies..."
for dep in "${DEPENDENCIES[@]}"; do
    if ! command -v "$dep" >/dev/null 2>&1; then
        echo "Missing: $dep"
        missing_deps+=("$dep")
    else
        echo "Found: $dep"
    fi
done

# dependencies
if [ "${#missing_deps[@]}" -ne 0 ]; then
    echo
    echo "The following dependencies are missing:"
    printf ' - %s\n' "${missing_deps[@]}"
    echo
    read -r -p "Do you want to install them? (y/N): " answer

    if [[ "$answer" == "y" || "$answer" == "Y" ]]; then
        if command -v apt-get >/dev/null 2>&1; then
            sudo apt-get install -y "${missing_deps[@]}"
        elif command -v brew >/dev/null 2>&1; then
            brew install "${missing_deps[@]}"
        else
            echo "No supported package manager found. Install dependencies manually."
            exit 1
        fi
    else
        echo "Installation declined. Exiting."
        exit 1
    fi
fi

# request mods
echo
echo "Fetching Steam collection data..."

curl -s -X POST \
  -H "Content-Type: application/x-www-form-urlencoded" \
  --data "collectioncount=1&publishedfileids[0]=3153577232" \
  "https://api.steampowered.com/ISteamRemoteStorage/GetCollectionDetails/v1/" \
  -o mods.txt

# destroys useless text
tmpfile=$(mktemp)

grep -o '"publishedfileid":"[0-9]*"' mods.txt \
| grep -o '[0-9]*' \
> "$tmpfile"

tail -n +2 "$tmpfile" > mods.txt

echo "Done. Extracted mod IDs saved to mods.txt"
```
after which I was left with the text file that doesn't want to download because of a similar error see #6

**Comment by duldamonet1** [comment]
My application is currently showing “could not determine the appID for the mods” when I try to download mods using mods.txt. How can I fix this?

**Comment by Noellelivinggayness** [comment]
> My application is currently showing “could not determine the appID for the mods” when I try to download mods using mods.txt. How can I fix this?

I don't think this tool works at all at the moment try an alternative
https://github.com/imwaitingnow/WorkshopDL

**Comment by alpergur13** [comment]
Sorry we took too long, new version released, it should work now, i think.

**Comment by Noellelivinggayness** [comment]
> Sorry we took too long, new version released, it should work now, i think.

not resolved

Fetching item: 3153577232...      //collection
Error: Unknown item type or item not found
Fetching item: 3032995884...      //mod
Error: Unknown item type or item not found

**Comment by Noellelivinggayness** [comment]
also I hate how it's no longer contained in the downloaded folder

**Comment by alpergur13** [comment]
Yeah the initial problem of yours seems to be not resolved, i don't know why it doesn't work but if you tried manually and it didn't work then it is not about our program.
If i got it wrong please tell.

Also about it being in a different folder, It was a tradeoff, it is far more easy to set up now, but some people may prefer setting download location, maybe we should add that as an extra option.

**Comment by duldamonet1** [comment]
I’m facing a similar issue, has a solution been found yet?

**Comment by Noellelivinggayness** [comment]
> Yeah the initial problem of yours seems to be not resolved, i don't know why it doesn't work but if you tried manually and it didn't work then it is not about our program. If i got it wrong please tell.
> 
> Also about it being in a different folder, It was a tradeoff, it is far more easy to set up now, but some people may prefer setting download location, maybe we should add that as an extra option.

using SteamCMD manually does download the files

**Comment by Noellelivinggayness** [comment]
> I’m facing a similar issue, has a solution been found yet?

try an alternative
https://github.com/imwaitingnow/WorkshopDL
